### ISSUE TITLE
How to do?

### ISSUE THREAD

**Issue by ChangQing-SH** [MarinManuel/PulsePalGUI#1]
Hi ,

I want to manually control the output, but the channel will be used for the optogenetics and after channel 1 is finished, the channel immediately output for an electric stim, is it possible that I can do this in this GUI?

**Comment by MarinManuel** [comment]
Hi,
I'm not sure I understand what you mean. Can you maybe draw a schema
showing what kind of output you are looking for?

**Comment by ChangQing-SH** [comment]
sorry for that, I want to do this:  when I click the button, channel 1 starts a pulse train, and after channel 1 is finished, channel 2 immediately output another pulse train. 
![1716527246462](https://github.com/MarinManuel/PulsePalGUI/assets/48444988/91fb440b-db29-425d-8d12-2760c19a837b)

**Comment by MarinManuel** [comment]
You can calculate the duration of Channel 1 (in Channel 1 tab, take the value Train delay + Train duration) and use that value as Channel 2 "Train Delay" (+ additional delay if you want some time between the end of Train 1 and the beginning of Train 2).
In the "Manuel Trigger" box at the bottom, check both Channel 1 and Channel 2, and click on "Trigger".
Does that work?

**Comment by ChangQing-SH** [comment]
the logic seems right, but I got some weird issue, the channel 1 can correctly manual trigger, but channel2 with only one pulse, and if I just trigger channel 2 or 3 or 4, only one pulse, it seems a bug, only channel 1 works.

**Comment by MarinManuel** [comment]
I see, this seems to be a bug on my end, where although the default settings are correctly applied to Channel 1, the defaults for channel 2-4 are not correctly applied and trying to trigger those channels does not work.

While I investigate the issue, you can fix the problem but switching Channel 2 to bipolar and back to monopolar. After that, the correct settings should be applied and you should be able to trigger the train on channel 2 (after a delay if you wish)

**Comment by MarinManuel** [comment]
I added a fix that should make the trains work as expected now, and you should be able to set the two trains to chain as discussed above. Please update to the latest version and let me know if that works

**Comment by ChangQing-SH** [comment]
@MarinManuel thanks, it works well, and this GUI is very easy to do, 
btw, The GUI try to find a port at the beginning, when I run the GUI, if I don;t connect with a pulsepal, it raises an error,  Could you fix this? just list all the pulsepal ports under the file menu, and the user can select which one to connect?  and also if click the connect, no any tips, it seems the GUI connects the port when I run the GUI, not with the connect click event.
